#Required sudo for docker
sudo: required

env:
  - distro: centos7
 
services:
  - docker

before_install:
#pull the image from Docker Hub for the OS under test
  - docker pull centos:7

script:
#create a random file to store the container
  - container_id=bitroid

# Run container detached
  - docker run --detach --name ${container_id} centos:7
  - docker exec --tty ${container_id} env TERM=xterm bash -c "./csv2dsv.sh"
  - docker stop 
