services: docker
language: bash

env:
  - distro: centos7
script:
    # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - sudo docker exec --tty ${container_id} ./csv2dsv.sh
