#Required sudo for docker
sudo: required
language: bash
branches:
  only:
  - ubuntu

before_install:
# Installing required packages
  - apt-get update
  - apt-cache search column > Package.txt
  - apt-get -y install $(cat Package.txt)

script:
# Initialize testing
  - ./csv2dsv.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
