#Required sudo for docker
sudo: required
language: bash
branches:
  only:
  - ubuntu

before_install:
# Installing required packages
  - sudo apt-get update
  - sudo apt-cache search column > Package.txt
  - sudo apt-get -y install $(cat Package.txt)

script:
# Initialize testing
  - ./csv2dsv.sh
#Notification point
notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
