services: docker
language: bash

before_script:
docker pull centos:7

script:
docker run -it --name temp centos /bin/bash
yum install git
git clone https://github.com/hemanth22/CSVToCustomDSV.git
cd CSVToCustomDSV
./csv2dsv.sh
exit
