version: 2
jobs:
     build:
       docker:
         - image: centos:latest
       steps:
         - checkout
         - run: 
             name: Identifying the Operating System.
             command: cat /etc/*release

         - run: 
             name: Installing Extra Packages for Enterprise Linux.
             command: yum install -y epel-release

         - run: 
             name: Installing Version control tool.
             command: yum install -y git

         - run: 
             name: Installing linux utilites.
             command: yum install -y util-linux.x86_64 fpaste

         - run: 
             name: Executing tests on App.
             command: cat ESS.csv | column -t -s '"' -o '' | column -t -s ',' -o ';' > ESS.txt

         - run: 
             name: Check execution result.
             command: cat ESS.txt | fpaste.noarch
